### ISSUE TITLE
documentation on concepts, terminology

### ISSUE THREAD

**Issue by erikbergsma** [allegro/vaas#160]
Wanted to leave feedback that for someone that is only familiar with what varnish can do, there are a lot of concepts and terminology thrown at you at https://vaas.readthedocs.io/en/latest/ which are almost not explained.
- directors
- probes
- hints
- database
- servers, dc, clusters

The documentation can do with either links to the varnish documentation, or a warning what vaas is aimed for people with an advanced understanding of varnish.

Where the explanation of these is missing, but also generic architecture advice is lacking. How do the concepts interact with each other, how many replicas of the database are needed, what db tech is used, how many instances of the various types of instances are recommended, what data needs to be persistent, general architecture advice etc.

**Comment by szymi-** [comment]
Thank you for your feedback. VaaS is a configuration tool for Varnish, and the project's documentation only relates to VaaS itself. Varnish concepts are best described in Varnish documentation, and any our attempt at documenting them here would not be near as good. With regards to database, VaaS is based on Django framework. We rely on Django to handle any database interaction. Therefore any database backend supported by Django can be used with VaaS. Replication and data persistence are out of scope of VaaS documentation.

Apart from the documentation, we provide Vagrant box with preconfigured Varnish servers to give any potential user a feel of how VaaS works. A lightweight Docker image is also available for testing. We successfully use VaaS in our environment and published it as is in hope there may be people out there who will find it useful. We only have limited resources we can assign to this project, therefore any input from the open source community, including improving the documentation, would be welcome.
