### ISSUE TITLE
Install failure on python 2.7-3.5

### ISSUE THREAD

**Issue by alessandroG77** [allegro/vaas#212]
Hi,
i've tried to install Vaas but i'v notice that its impossible for errata required package.

On setup, python 3.5 + is required.
https://vaas.readthedocs.io/en/latest/quick-start/production/
Ok, i create virtual env on python 3.7, but following modules required:
pip install python-ldap==2.4.15
pip install django-auth-ldap==1.2.0
pip install MySQL-python==1.2.3
pip install lck.django
pip install uwsgi

Are for python 2.7 version...

**Comment by awmackowiak** [comment]
@alessandroG77 thanks for replay. We will update doc soon.

**Comment by alessandroG77** [comment]
Ok, thanks a lot. 
I'l wait for your updates...:)

Best,
Alessandro.

**Comment by alessandroG77** [comment]
Any News?

Thanks a lot.

**Comment by alessandroG77** [comment]
Thanks a lot....
