### ISSUE TITLE
Specific Tags

### ISSUE THREAD

**Issue by icrunchbanger** [allegro/vaas#245]
Hi guys,

First of all thank you for a great work.
Second one, im sorry if this is not really an issue and i am just missing something very obvious. 

So lets get to the chase.
Im am having issues sending specific tag via vaas.
If i send purge request locally on Varnish instance i am getting wanted results:
`curl -v -X PURGE -H 'X-Magento-Tags-Pattern: .*' http://localhost/rs/muskarci/obuca/mokasine`
  <head>
    <title>200 Purged</title>
  </head>
  <body>
    <h1>Error 200 Purged</h1>
    <p>Purged</p>
    <h3>Guru Meditation:</h3>
    <p>XID: 2163377</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>

But when i try sending same request via vaas im am getting:
-   RespStatus     400
-   RespReason     Bad Request
-   RespReason     X-Magento-Tags-Pattern or X-Pool header required
-   VCL_call       SYNTH

I have added Varnish template used to the vaas configuration and tried adding VCL template block requesting usage of this tag. 
What is the right syntax for sending this tag via VCL template block?
Am i missing something here?

Keep up the good work.
Kind regards.

**Comment by awmackowiak** [comment]
hey @icrunchbanger , 
in default we don't add purge method in vcl template because you need to setup **acl** for this.
https://varnish-cache.org/docs/trunk/users-guide/purging.html#http-purging
Give as note if it works :)

**Comment by awmackowiak** [comment]
For no more response i close the issue.
