### ISSUE TITLE
Invalid syntax - Python 3.9

### ISSUE THREAD

**Issue by ofthef** [allegro/vaas#297]
Hi,

I'm trying to deploy vaas on Ubuntu 20 following these steps:

https://vaas.readthedocs.io/en/latest/quick-start/production/

I'm stucked in this step:

_pip install lck.django_

I'm getting a lot of errors like this one:

    _----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/88/59/82c73ff573b7ed1b7a831cd51f81cff351fa53514bcd1851e522deb2a9ec/distribute-0.6.2.zip#sha256=5bd8ebc58dea3659ded73f1b8fd070b09e6e22acb1b5745686c743e2782d53ee (from https://pypi.org/simple/distribute/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  Using cached distribute-0.6.2.tar.gz (518 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/economiadigital/vaas/vaas-app/prod-env/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dc1qa8ti/distribute_e7b70ef6b69741b096bf87ce62ac6ddc/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dc1qa8ti/distribute_e7b70ef6b69741b096bf87ce62ac6ddc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-1rbrgzya
         cwd: /tmp/pip-install-dc1qa8ti/distribute_e7b70ef6b69741b096bf87ce62ac6ddc/
    Complete output (10 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-dc1qa8ti/distribute_e7b70ef6b69741b096bf87ce62ac6ddc/setuptools/__init__.py", line 2, in <module>
        from setuptools.extension import Extension, Library
      File "/tmp/pip-install-dc1qa8ti/distribute_e7b70ef6b69741b096bf87ce62ac6ddc/setuptools/extension.py", line 2, in <module>
        from setuptools.dist import _get_unpatched
      File "/tmp/pip-install-dc1qa8ti/distribute_e7b70ef6b69741b096bf87ce62ac6ddc/setuptools/dist.py", line 102
        except ValueError, e:
                         ^
    SyntaxError: invalid syntax
    ----------------------------------------_

And finally:

_ERROR: Cannot install lck-django==0.5.0, lck-django==0.5.1, lck-django==0.5.2, lck-django==0.5.3, lck-django==0.5.4, lck-django==0.5.5, lck-django==0.5.6, lck-django==0.5.7, lck-django==0.5.8, lck-django==0.6.0, lck-django==0.6.1, lck-django==0.6.2, lck-django==0.6.3, lck-django==0.6.4, lck-django==0.6.5, lck-django==0.6.6, lck-django==0.6.7, lck-django==0.7.0, lck-django==0.7.1, lck-django==0.7.10, lck-django==0.7.11, lck-django==0.7.12, lck-django==0.7.13, lck-django==0.7.14, lck-django==0.7.2, lck-django==0.7.3, lck-django==0.7.4, lck-django==0.7.5, lck-django==0.7.6, lck-django==0.7.7, lck-django==0.7.8, lck-django==0.7.9, lck-django==0.8.0, lck-django==0.8.1, lck-django==0.8.10, lck-django==0.8.2, lck-django==0.8.3, lck-django==0.8.4, lck-django==0.8.5, lck-django==0.8.6, lck-django==0.8.7, lck-django==0.8.8 and lck-django==0.8.9 because these package versions have conflicting dependencies.

The conflict is caused by:
    lck-django 0.8.10 depends on distribute
    lck-django 0.8.9 depends on distribute
    lck-django 0.8.8 depends on distribute
    lck-django 0.8.7 depends on distribute
    lck-django 0.8.6 depends on distribute
    lck-django 0.8.5 depends on distribute
    lck-django 0.8.4 depends on distribute
    lck-django 0.8.3 depends on distribute
    lck-django 0.8.2 depends on distribute
    lck-django 0.8.1 depends on distribute
    lck-django 0.8.0 depends on distribute
    lck-django 0.7.14 depends on distribute
    lck-django 0.7.13 depends on distribute
    lck-django 0.7.12 depends on distribute
    lck-django 0.7.11 depends on distribute
    lck-django 0.7.10 depends on distribute
    lck-django 0.7.9 depends on distribute
    lck-django 0.7.8 depends on distribute
    lck-django 0.7.7 depends on distribute
    lck-django 0.7.6 depends on distribute
    lck-django 0.7.5 depends on distribute
    lck-django 0.7.4 depends on distribute
    lck-django 0.7.3 depends on distribute
    lck-django 0.7.2 depends on distribute
    lck-django 0.7.1 depends on distribute
    lck-django 0.7.0 depends on distribute
    lck-django 0.6.7 depends on distribute
    lck-django 0.6.6 depends on distribute
    lck-django 0.6.5 depends on distribute
    lck-django 0.6.4 depends on distribute
    lck-django 0.6.3 depends on distribute
    lck-django 0.6.2 depends on distribute
    lck-django 0.6.1 depends on distribute
    lck-django 0.6.0 depends on PIL>=1.1.7
    lck-django 0.5.8 depends on PIL>=1.1.7
    lck-django 0.5.7 depends on PIL>=1.1.7
    lck-django 0.5.6 depends on PIL>=1.1.7
    lck-django 0.5.5 depends on PIL>=1.1.7
    lck-django 0.5.4 depends on PIL>=1.1.7
    lck-django 0.5.3 depends on PIL>=1.1.7
    lck-django 0.5.2 depends on PIL>=1.1.7
    lck-django 0.5.1 depends on PIL>=1.1.7
    lck-django 0.5.0 depends on PIL>=1.1.7

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies_

Could you help with this issue?

**Comment by awmackowiak** [comment]
The fixes was merges in #298.
You can check it out
