### ISSUE TITLE
Identifiers a bit to short for descriptive name

### ISSUE THREAD

**Issue by pawelbres** [allegro/vaas#94]
Hi,

since we are currently creating many environments and they all have unique identifiers that have at least 32 characters and we combine them with static names of default identifiers used in vaas it is quite hard to squeeze it into 50 or 20 characters used as uniqe name of:
- vcl template
- vcl template block
- director
- logical cluster

Since it is in all above cases unique field of varchar in mysql I would like to see 100 chars length.

**Comment by awmackowiak** [comment]
Merged. Closed
